"""Initial migration for AgroAE

Revision ID: 1479a74e9f6d
Revises:
Create Date: 2026-08-05 07:01:59.540376

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1479a74e9f6d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farm_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_name", sa.String(), nullable=True),
        sa.Column("location_coordinates", sa.String(), nullable=True),
        sa.Column("soil_type", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_farm_sites_id"), "farm_sites", ["id"], unique=False)
    op.create_index(
        op.f("ix_farm_sites_site_name"), "farm_sites", ["site_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_farm_sites_site_name"), table_name="farm_sites")
    op.drop_index(op.f("ix_farm_sites_id"), table_name="farm_sites")
    op.drop_table("farm_sites")
    # ### end Alembic commands ###
